{
 "title": "testDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "number of threads pr image",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_num_threads" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes / 1024 / 1024"
    }
   ]
  },
  {
   "title": "avg. response time pr request",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (action)(http_request_duration_seconds_sum) / sum by (action) (http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Requests pr minute",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by (action)(http_requests_in_progress)"
    }
   ]
  }
 ]
}